
;; (defun -charCodeAt (str pos)
;;   (if (< pos (length str))
;;       (let ((ch1 (elt str pos)))
;; 	(- ch1 97)
;; 	)
;;     -1)
;;   )

(defun -charCodeAt (str pos)
  (if (< pos (length str))
      (- (elt str pos) 97)
    -1)
  )

(defun cfor (&rest params)
  (let ((init-val (plist-get params :init))
	(conds (plist-get params :when))
	(next-val-func (plist-get params :next))
	(body (plist-get params :body)))
    
    (let ((curr-val init-val))
      (while (funcall conds curr-val)
	(when body
	  (funcall body curr-val)
	  )
	(setq curr-val (funcall next-val-func curr-val))
	)
      )
    )
  )

;; (let ()
;;   (print "================")
;;   (cfor :init 0 :when (lambda(x) (< x 5)) :next '1+ :body (lambda(x) (print "-")))
;;   (print "================")
;;   )

(defun bm_compile_pattern (pattern)
  (let* ((R 256) (M (length pattern)) (right (make-vector R -1)))
    (let ((j -1))
      (while (progn (setq j (1+ j)) (< j M))
	(aset right (-charCodeAt pattern j) j) ) )
    right
    )
  )

;;(bm_compile_pattern "abcdb")

(defun bm_substring_search (pattern text)
  (let ((N (length text)) (M (length pattern))
	(right nil) (skip 0) (result nil))
    
    (setq right (bm_compile_pattern pattern))
    (let ((i nil) (j nil))      
      (while (progn (setq i (if (not i) 0 (+ i skip)) )
       		    (and (not result) (<= i (- N M))) )
	(setq skip 0)
	(let ((endLoop nil))
	  (while (progn (setq j (if (not j) (1- M) (1- j) ))
			(and (not endLoop) (>= j 0)))
	    (when (/= (-charCodeAt pattern j) (-charCodeAt text (+ i j)))
	      (setq skip (- j (aref right (-charCodeAt text (+ i j)))))
	      (when (< skip 1) (setq skip 1))
	      (setq endLoop 1)
	      )
	    )
	  )
	(when (= 0 skip) (setq result i))
	)
      )
    (if result result N)
    )
  )

(bm_substring_search "aabb" "zzaabbe")
